# File I/O
- This section will help me understand how to load and save results or data from Disk 

In [1]:
import torch
from torch import nn
from torch.nn import functional as F


In [2]:
x = torch.arange(4)
# Save a tensor
torch.save(x, 'x-file')


In [3]:
# Load tensor from file `x-file`
x2 = torch.load("x-file")
x2

tensor([0, 1, 2, 3])

In [4]:
y = torch.zeros(4)
torch.save([x, y],'x-files')
x2, y2 = torch.load('x-files')
(x2, y2)


(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [5]:
# We can save a dictionary or even lists
mydict = {"x": x, "y": y}
torch.save(mydict, "mydict")
mydict2 = torch.load("mydict")
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [6]:
# Finally we can save a model at a particular state to disk and load it later
# This is done by storing the parameters
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.LazyLinear(256)
        self.output = nn.LazyLinear(10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)


/home/sih/miniconda3/envs/d2l/lib/python3.9/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [7]:
torch.save(net.state_dict(), 'mlp.parameters')

In [8]:
torch.load('mlp.parameters')

OrderedDict([('hidden.weight',
              tensor([[-0.0406, -0.0169,  0.1534,  ..., -0.1299, -0.2089,  0.1654],
                      [-0.1344, -0.2185, -0.0614,  ..., -0.0782,  0.2068,  0.0558],
                      [-0.1868,  0.1597,  0.0736,  ..., -0.2019,  0.2121, -0.2121],
                      ...,
                      [-0.0317,  0.0709, -0.0387,  ...,  0.2012,  0.1614, -0.1359],
                      [-0.0844,  0.1391, -0.2071,  ...,  0.1102,  0.1514,  0.0312],
                      [-0.1129,  0.2140, -0.1225,  ..., -0.0887, -0.0540,  0.0505]])),
             ('hidden.bias',
              tensor([ 0.0074, -0.0040, -0.0580,  0.0221, -0.0811,  0.0756,  0.0103, -0.1469,
                       0.1645, -0.1613, -0.1643, -0.2178, -0.1158, -0.1434, -0.1250, -0.0504,
                      -0.1854,  0.0131,  0.1311,  0.1596, -0.1383, -0.1438,  0.0212, -0.2230,
                      -0.2089,  0.1713, -0.1243, -0.1652,  0.1485,  0.0142,  0.2021, -0.2169,
                      -0.0281,

In [9]:
# most imporatntly we can recover a new model at that state
clone = MLP()
clone.load_state_dict(torch.load('mlp.parameters'))
clone.eval()

/home/sih/miniconda3/envs/d2l/lib/python3.9/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


MLP(
  (hidden): LazyLinear(in_features=0, out_features=256, bias=True)
  (output): LazyLinear(in_features=0, out_features=10, bias=True)
)